import prisma from "../lib/prisma";

const STATUSES = ["OPEN", "RESOLVED", "CLOSED"] as const;
const CATEGORIES = [
  "GENERAL_QUESTION",
  "TECHNICAL_QUESTION",
  "REFUND_REQUEST",
  null,
] as const;

const tickets: {
  subject: string;
  body: string;
  senderName: string;
  senderEmail: string;
  status: (typeof STATUSES)[number];
  category: (typeof CATEGORIES)[number];
  daysAgo: number;
}[] = [
  // TECHNICAL_QUESTION — OPEN
  {
    subject: "Cannot log in after password reset",
    body: "I reset my password yesterday but I still cannot log in. The page just shows 'Invalid credentials' even with the new password. I've tried clearing cache and using incognito mode.",
    senderName: "Alice Morrison",
    senderEmail: "alice.morrison@example.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "API rate limit errors in production",
    body: "We're seeing 429 errors from your API starting this morning around 9am UTC. Our request volume hasn't changed. Can you check if the rate limits were lowered? We're on the Business plan.",
    senderName: "Dev Team at Acme",
    senderEmail: "devops@acmecorp.io",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 0,
  },
  {
    subject: "Webhook not firing on order completion",
    body: "Our webhook endpoint is configured and verified, but we stopped receiving events for order.completed around 3 days ago. Other event types still work fine.",
    senderName: "James Hartley",
    senderEmail: "james@shopfront.dev",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 3,
  },
  {
    subject: "2FA setup screen shows blank page",
    body: "When I navigate to Settings > Security > Enable Two-Factor, the page is completely blank. No error in the browser console. Tested on Chrome 124 and Firefox 126.",
    senderName: "Priya Nair",
    senderEmail: "priya.nair@finco.in",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 2,
  },
  {
    subject: "CSV export includes duplicate rows",
    body: "Every time I export the transactions report to CSV, each row appears twice. This started happening after last week's update. The in-app table shows correct data.",
    senderName: "Oliver Krause",
    senderEmail: "oliver.krause@bookkeeping.de",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 5,
  },
  {
    subject: "SSO login redirects to 404",
    body: "Our Okta SSO integration stopped working. Users are redirected to /sso/callback and get a 404. The ACS URL in our SAML settings hasn't changed.",
    senderName: "HR Department",
    senderEmail: "hr-tech@globalcorp.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "Mobile app crashes on launch after update",
    body: "After updating to v3.2.1 on iOS 17.4, the app crashes immediately on launch. Downgrading to v3.2.0 fixes it. I've submitted a crash log — report ID #CR-20840.",
    senderName: "Fatima Al-Rashid",
    senderEmail: "fatima.rashid@icloud.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 0,
  },
  {
    subject: "Bulk user import failing silently",
    body: "I'm uploading a CSV of 500 users. The import says it succeeded but only 12 users appear in the system. No error message is shown. File attached to this ticket.",
    senderName: "System Admin, RegionalBank",
    senderEmail: "sysadmin@regionalbank.org",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 4,
  },

  // TECHNICAL_QUESTION — RESOLVED
  {
    subject: "Email notifications not being received",
    body: "None of my team members are getting email notifications for new assignments. We checked spam folders. The sending domain is verified in our DNS.",
    senderName: "Sophie Laurent",
    senderEmail: "sophie.laurent@agence-paris.fr",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 10,
  },
  {
    subject: "Dashboard charts not loading — spinner forever",
    body: "The analytics dashboard shows a loading spinner that never resolves. Network tab shows a 500 error from /api/reports/summary. This is urgent for an exec review tomorrow.",
    senderName: "Kwame Asante",
    senderEmail: "k.asante@ventures.gh",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 7,
  },
  {
    subject: "Date filter returning wrong results",
    body: "When I filter transactions between Jan 1 and Jan 31, I'm seeing records from December. I think the filter is off by one timezone. We're in UTC+5:30.",
    senderName: "Ravi Shankar",
    senderEmail: "ravi.s@tradehouse.in",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 14,
  },
  {
    subject: "Search autocomplete stopped working",
    body: "The search bar no longer shows autocomplete suggestions as I type. It was working last week. Tested on Edge and Safari — same behavior on both.",
    senderName: "Hannah Schmidt",
    senderEmail: "h.schmidt@logistik.de",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 12,
  },
  {
    subject: "PDF reports have garbled text",
    body: "Generated PDFs from the reporting module show garbled characters for accented letters (é, ü, ñ). Plain text in the app is fine. Only the PDF export is affected.",
    senderName: "Carlos Vega",
    senderEmail: "c.vega@editorial.mx",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 20,
  },
  {
    subject: "OAuth integration returns invalid_grant",
    body: "Our Google OAuth login returns 'invalid_grant' for some users but not others. We're using the standard authorization_code flow. Refresh tokens are stored in our DB.",
    senderName: "Engineering, Stackify",
    senderEmail: "eng@stackify.io",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 18,
  },

  // TECHNICAL_QUESTION — CLOSED
  {
    subject: "File uploads limited to 5MB — plan says 50MB",
    body: "Our Pro plan advertises 50MB file uploads but the system rejects anything over 5MB with a 413 error. Is there a server-side configuration we need to change?",
    senderName: "Miriam Cohen",
    senderEmail: "mcohen@designstudio.il",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 30,
  },
  {
    subject: "API keys not working after account migration",
    body: "We migrated from the legacy plan to the new Enterprise plan. All our API keys returned 401 after the migration. We've tried regenerating but new keys also fail.",
    senderName: "Platform Team, Nordicsoft",
    senderEmail: "platform@nordicsoft.se",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 25,
  },
  {
    subject: "Scheduled reports not sending on weekends",
    body: "Our weekly summary report is configured to send every Sunday at 8am. It has never sent on a Sunday. Manual sends work fine. Our timezone is set to America/New_York.",
    senderName: "Ops Team, SunriseMedia",
    senderEmail: "ops@sunrisemedia.com",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 40,
  },
  {
    subject: "Stripe webhook signature verification failing",
    body: "Our Stripe webhook handler is returning 400 for all events. The signing secret is correct. We suspect the issue is that we're reading the raw body after Express middleware parses it.",
    senderName: "Backend Dev, Checkoutly",
    senderEmail: "backend@checkoutly.co",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 35,
  },

  // REFUND_REQUEST — OPEN
  {
    subject: "Charged twice for March subscription",
    body: "My credit card statement shows two charges of $49.00 on March 3rd from your company. My account only has one subscription. Please refund the duplicate charge.",
    senderName: "Thomas Griffin",
    senderEmail: "tom.griffin@gmail.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 2,
  },
  {
    subject: "Annual plan auto-renewed without warning",
    body: "My annual plan renewed on April 1st and I was charged $588. I didn't receive any renewal reminder. I'd like a full refund as I was planning to cancel — I haven't used the service since January.",
    senderName: "Laura Petersen",
    senderEmail: "laura.p@outlook.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 1,
  },
  {
    subject: "Refund for unused seats on cancelled account",
    body: "We cancelled our team account on March 15th with 18 days remaining in the billing cycle. We had 10 seats at $30/month each. Requesting a pro-rated refund of $180.",
    senderName: "Finance, Brightpath Ltd",
    senderEmail: "accounts@brightpath.co.uk",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 3,
  },
  {
    subject: "Charged for plan I downgraded from",
    body: "I downgraded from Pro to Free last month but was still charged $29 this month. My billing page shows the Free plan but the charge still appeared on my bank statement.",
    senderName: "Aiko Tanaka",
    senderEmail: "aiko.tanaka@hotmail.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 0,
  },
  {
    subject: "Refund requested — product not as described",
    body: "I purchased the Advanced Analytics add-on based on the feature list on your pricing page. However, the cohort analysis feature shown in screenshots is not available in the actual product.",
    senderName: "Brendan Walsh",
    senderEmail: "b.walsh@marketdata.ie",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 4,
  },

  // REFUND_REQUEST — RESOLVED
  {
    subject: "Payment taken after free trial ended early",
    body: "I cancelled during the free trial period on the 12th but was charged $59 on the 14th. My cancellation confirmation email is timestamped before the charge.",
    senderName: "Ingrid Bjork",
    senderEmail: "ingrid.bjork@me.com",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    daysAgo: 8,
  },
  {
    subject: "Duplicate payment — PayPal and card both charged",
    body: "During checkout my PayPal declined so I switched to my credit card. Both ended up being charged. Order ID: #ORD-88821. Total charged: $118 instead of $59.",
    senderName: "Roberto Esposito",
    senderEmail: "r.esposito@libero.it",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    daysAgo: 15,
  },
  {
    subject: "Wrong price charged — promo code not applied",
    body: "I applied promo code SAVE30 at checkout but was charged the full $79 instead of $55.30. The page showed the discount applied before I confirmed payment.",
    senderName: "Nina Petrov",
    senderEmail: "nina.petrov@yandex.ru",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    daysAgo: 11,
  },
  {
    subject: "Refund for cancelled conference add-on",
    body: "We purchased 5 tickets for the annual user conference ($150 each). The event was cancelled by your team. Requesting a full refund of $750.",
    senderName: "Events Coordinator, TechBridge",
    senderEmail: "events@techbridge.org",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    daysAgo: 22,
  },

  // REFUND_REQUEST — CLOSED
  {
    subject: "Subscription refund — bought wrong plan",
    body: "I accidentally purchased the Business plan instead of Pro. I realised within 10 minutes and haven't used any Business features. Please refund the difference ($70).",
    senderName: "Yusuf Adeola",
    senderEmail: "y.adeola@consult.ng",
    status: "CLOSED",
    category: "REFUND_REQUEST",
    daysAgo: 45,
  },
  {
    subject: "Refund — service down during billing period",
    body: "Your service was down for 4 days in February (Feb 7-10). This represents 14% of our monthly billing period. We're requesting a 14% credit or refund on our $200 plan.",
    senderName: "Ops Manager, Streamline Inc",
    senderEmail: "ops-manager@streamline-inc.com",
    status: "CLOSED",
    category: "REFUND_REQUEST",
    daysAgo: 50,
  },
  {
    subject: "Mistaken purchase — used wrong account",
    body: "I have two accounts and accidentally purchased a plan upgrade on my personal account instead of my business account. I need a refund to the personal account so I can buy it on the right one.",
    senderName: "Claire Fontaine",
    senderEmail: "claire.fontaine@perso.fr",
    status: "CLOSED",
    category: "REFUND_REQUEST",
    daysAgo: 60,
  },

  // GENERAL_QUESTION — OPEN
  {
    subject: "How do I transfer account ownership?",
    body: "Our original account owner has left the company. How can we transfer ownership to our new IT manager? We still have access to the original owner's work email.",
    senderName: "IT Department, Meridian Co",
    senderEmail: "it@meridian-co.com",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "What is the data retention policy?",
    body: "We're completing a vendor assessment and need to know your data retention policy — specifically how long user activity logs are kept and how they can be exported or deleted on request.",
    senderName: "Compliance Team, FinSecure",
    senderEmail: "compliance@finsecure.eu",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 2,
  },
  {
    subject: "Can I use your service for a non-profit?",
    body: "We're a registered 501(c)(3) non-profit. Do you offer discounted pricing for non-profits? We currently have 8 staff members who would use the platform.",
    senderName: "Executive Director, HopeFirst",
    senderEmail: "director@hopefirst.org",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 3,
  },
  {
    subject: "Difference between Business and Enterprise plans",
    body: "Can you explain the key differences between the Business and Enterprise plans? Specifically around user limits, SLA guarantees, and dedicated support. We're a team of 45.",
    senderName: "Procurement, Albion Group",
    senderEmail: "procurement@albion-group.co.uk",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 0,
  },
  {
    subject: "Is there a desktop app available?",
    body: "We prefer not to use browser-based tools for security reasons. Is there a native desktop application available for Windows? If not, is it on the roadmap?",
    senderName: "Luisa Romero",
    senderEmail: "luisa.romero@secureops.es",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 4,
  },
  {
    subject: "GDPR data processing agreement request",
    body: "Under GDPR Article 28, we require a signed Data Processing Agreement before we can use your service with customer data. Can you provide a DPA or direct us to your DPA process?",
    senderName: "Legal, EuroCommerce GmbH",
    senderEmail: "legal@eurocommerce.de",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "Can multiple users share one login?",
    body: "We only have budget for one seat but three people need occasional access. Is sharing a login against your terms of service? Are there any lightweight read-only roles available?",
    senderName: "Maria Gonzalez",
    senderEmail: "maria.g@smallbiz.mx",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 2,
  },

  // GENERAL_QUESTION — RESOLVED
  {
    subject: "Do you offer SOC 2 Type II reports?",
    body: "Our security team requires a copy of your most recent SOC 2 Type II audit report before we can approve you as a vendor. Can you provide this under NDA?",
    senderName: "InfoSec, CapitalFund Partners",
    senderEmail: "infosec@capitalfund.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 9,
  },
  {
    subject: "What payment methods do you accept?",
    body: "We'd like to pay by invoice with NET-30 terms rather than by credit card. Is this available on the Business plan? We're a company of 25 based in the US.",
    senderName: "AP Department, Riverstone LLC",
    senderEmail: "ap@riverstone-llc.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 13,
  },
  {
    subject: "How do I add a secondary email to my account?",
    body: "I'd like to add my personal email as a backup in case I lose access to my work email. The profile settings only seem to show one email field.",
    senderName: "Derek Lin",
    senderEmail: "derek.lin@techstartup.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 16,
  },
  {
    subject: "Is there an affiliate or referral program?",
    body: "I recommend your product to clients regularly. Do you have a formal affiliate or referral program where I could earn commission or credits for successful referrals?",
    senderName: "Consultant, Hayden Advisory",
    senderEmail: "info@havenadvisory.ca",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 19,
  },
  {
    subject: "Supported languages for the interface",
    body: "Our team is based in Japan and our staff have limited English proficiency. Is the interface available in Japanese? If not, is localisation planned?",
    senderName: "Satoshi Yamamoto",
    senderEmail: "s.yamamoto@kaisha.jp",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 21,
  },
  {
    subject: "How long does account verification take?",
    body: "I signed up 48 hours ago and my account is still showing as 'pending verification'. The verification email link worked but the account still shows the pending status.",
    senderName: "Chioma Obi",
    senderEmail: "chioma.obi@gmail.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 6,
  },

  // GENERAL_QUESTION — CLOSED
  {
    subject: "Requesting an invoice for tax purposes",
    body: "I need a proper VAT invoice for my subscription payment made on February 28th. The receipt in my account doesn't include my company VAT number. Company: Petrov Consulting, VAT: BG123456789.",
    senderName: "Dmitri Petrov",
    senderEmail: "d.petrov@petrov-consulting.bg",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 28,
  },
  {
    subject: "Can I pause my subscription instead of cancelling?",
    body: "I'm going on parental leave for 3 months. Rather than cancelling and losing my data and settings, can I pause my subscription and resume it when I'm back?",
    senderName: "Anna Bergström",
    senderEmail: "anna.bergstrom@gmail.com",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 33,
  },
  {
    subject: "Maximum number of API requests per day",
    body: "We're planning an integration and need to know the daily API request limits for each plan tier. The documentation page only mentions per-minute limits.",
    senderName: "Integration Partner, Connectify",
    senderEmail: "partners@connectify.dev",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 42,
  },
  {
    subject: "How to delete my account and all data",
    body: "I'd like to permanently delete my account and ensure all my personal data is removed from your systems, as per my rights under GDPR. Please confirm the deletion timeline.",
    senderName: "Martin Dubois",
    senderEmail: "martin.dubois@protonmail.com",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 55,
  },
  {
    subject: "Office hours for live chat support",
    body: "What are the hours when live chat support is available? I'm based in Sydney (AEST) and keep missing the window. Is there a way to schedule a callback?",
    senderName: "Chloe Park",
    senderEmail: "chloe.park@aussietech.com.au",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 38,
  },

  // Null category — mixed statuses
  {
    subject: "Feedback: onboarding flow is confusing",
    body: "I wanted to share some feedback. The onboarding wizard skips several steps without explanation and the progress bar jumps from 40% to 90% suddenly. It's making it hard to know what's expected.",
    senderName: "Amelia Stone",
    senderEmail: "amelia.stone@startup.com",
    status: "OPEN",
    category: null,
    daysAgo: 1,
  },
  {
    subject: "Suggestion: dark mode for the dashboard",
    body: "I work late hours and the bright white dashboard is straining my eyes. Would really appreciate a dark mode option. Many of your competitors offer this. Happy to beta test if you build it.",
    senderName: "Elijah Brooks",
    senderEmail: "e.brooks@devhouse.com",
    status: "OPEN",
    category: null,
    daysAgo: 3,
  },
  {
    subject: "Wrong company name displayed in header",
    body: "After updating our company name in Settings, the old name still shows in the top navigation bar. A hard refresh doesn't fix it. It's been 2 days since the change.",
    senderName: "Ops, RenamedCo",
    senderEmail: "ops@renamedco.com",
    status: "RESOLVED",
    category: null,
    daysAgo: 8,
  },
  {
    subject: "Request: bulk export of all historical data",
    body: "We're migrating to a new system and need a complete export of all our data — tickets, users, activity logs — going back to account creation in 2021. Can this be arranged?",
    senderName: "CTO, Horizon Systems",
    senderEmail: "cto@horizon-systems.net",
    status: "OPEN",
    category: null,
    daysAgo: 2,
  },
  {
    subject: "Accessibility issue: screen reader not reading table",
    body: "Our team includes a visually impaired employee who uses NVDA with Chrome. The main data table is not being read aloud correctly — the screen reader skips column headers. This is blocking their workflow.",
    senderName: "HR, Inclusive Works",
    senderEmail: "hr@inclusiveworks.org",
    status: "OPEN",
    category: null,
    daysAgo: 0,
  },
  {
    subject: "Slow performance on large datasets",
    body: "When our account has more than 10,000 records, the list views become extremely slow to load — sometimes over 30 seconds. This is a significant performance issue for us.",
    senderName: "CTO, DataScale Corp",
    senderEmail: "cto@datascale.io",
    status: "RESOLVED",
    category: null,
    daysAgo: 17,
  },
  {
    subject: "Typo on the pricing page",
    body: "The Enterprise plan pricing page says 'Unlimted storage' — missing an 'i' in Unlimited. Small thing but wanted to flag it.",
    senderName: "Nadia Okonkwo",
    senderEmail: "nadia.o@workemail.com",
    status: "CLOSED",
    category: null,
    daysAgo: 44,
  },
  {
    subject: "Feature request: custom email templates",
    body: "Could you add the ability to customise the transactional email templates? We'd love to match the style to our brand. Even basic variable substitution would be a great start.",
    senderName: "Marketing, Bloom Agency",
    senderEmail: "marketing@bloom-agency.com",
    status: "CLOSED",
    category: null,
    daysAgo: 52,
  },

  // More TECHNICAL_QUESTION variety
  {
    subject: "GraphQL queries timing out on nested relations",
    body: "Queries that fetch users with nested orders and order items are timing out after 30s. Flat queries work fine. We're using the GraphQL endpoint on the Enterprise plan.",
    senderName: "Backend Lead, Netweave",
    senderEmail: "backend@netweave.dev",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "CORS error when calling API from custom domain",
    body: "We moved our frontend to app.ourcustomdomain.com and now all API calls fail with CORS errors. The domain is added to our allowed origins list in settings.",
    senderName: "Full Stack Dev, Cartify",
    senderEmail: "dev@cartify.io",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 2,
  },
  {
    subject: "Notification emails going to spam",
    body: "Several of our users report that system notification emails land in spam. Our domain has SPF and DKIM set up. Is there an IP allowlist we should add?",
    senderName: "IT Lead, BranchOut",
    senderEmail: "it@branchout.co",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 9,
  },
  {
    subject: "Broken image thumbnails after storage migration",
    body: "After migrating our files to the new storage region, all image thumbnails in the media library show broken links. The original files are accessible via direct URL.",
    senderName: "Content Team, PicVault",
    senderEmail: "content@picvault.com",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 11,
  },
  {
    subject: "Cannot revoke team member access",
    body: "I'm trying to remove a former employee from our workspace but the 'Remove member' button is greyed out for their account. They are not an admin. This is a security concern.",
    senderName: "Admin, GrowthPilot",
    senderEmail: "admin@growthpilot.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 0,
  },
  {
    subject: "Zapier integration failing on multi-step zaps",
    body: "Our Zapier integration works fine for single-step zaps. Multi-step zaps that include your app fail at the authentication step with 'Connection expired', even after reconnecting.",
    senderName: "Automation Specialist, FlowOps",
    senderEmail: "automation@flowops.co",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 3,
  },
  {
    subject: "Audit log missing entries from last week",
    body: "Our compliance team noticed that the audit log has a gap — entries from April 14th 09:00 to April 15th 06:00 UTC are missing. There were active users during that time.",
    senderName: "Compliance Officer, SecurePay",
    senderEmail: "compliance@securepay.io",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 4,
  },
  {
    subject: "Custom domain SSL certificate not renewing",
    body: "The SSL certificate for our custom domain portal.ourcompany.com expires in 5 days and has not auto-renewed. We set up auto-renewal 6 months ago when we added the domain.",
    senderName: "DevOps, Serverly",
    senderEmail: "devops@serverly.net",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "Pagination not working on mobile",
    body: "On mobile devices (tested on iPhone 14 and Samsung Galaxy S23), the pagination controls at the bottom of lists are not tappable. The buttons appear but don't respond to taps.",
    senderName: "QA Lead, Appspot",
    senderEmail: "qa@appspot.io",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 15,
  },
  {
    subject: "Data not syncing between team members in real time",
    body: "When one team member updates a record, other team members don't see the change until they hard-refresh the page. Your documentation says changes are pushed in real time.",
    senderName: "Product Manager, Collabify",
    senderEmail: "pm@collabify.team",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 23,
  },
  {
    subject: "IP whitelist not applying to new API keys",
    body: "We have an IP whitelist configured for our workspace. Newly created API keys seem to bypass this restriction and can be used from any IP. Existing keys respect the whitelist.",
    senderName: "Security Team, VaultOps",
    senderEmail: "security@vaultops.com",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 36,
  },
  {
    subject: "Timezone conversion incorrect in reports",
    body: "Scheduled reports always show times in UTC regardless of the workspace timezone setting (we're set to PST). This makes the data hard to interpret for our US-based team.",
    senderName: "Data Analyst, WestCoast Analytics",
    senderEmail: "analyst@wca.com",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    daysAgo: 47,
  },

  // More REFUND_REQUEST
  {
    subject: "Overcharged due to currency conversion error",
    body: "My plan is priced in USD but I was charged in GBP at an incorrect rate. I paid £85 but the equivalent should have been £74 at today's rate. Please refund the £11 difference.",
    senderName: "Ben Harrison",
    senderEmail: "ben.harrison@btinternet.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 1,
  },
  {
    subject: "Refund for add-on that wasn't activated",
    body: "I purchased the Priority Support add-on last month but it was never activated on my account — I'm still in the standard support queue. Requesting refund of $25.",
    senderName: "Wanjiku Kamau",
    senderEmail: "w.kamau@kenyatech.co.ke",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 2,
  },
  {
    subject: "Gift purchase for wrong recipient",
    body: "I purchased a 1-year subscription as a gift but entered the wrong email address. The recipient has not accepted yet. Can I cancel and reissue to the correct email?",
    senderName: "Patrick Dumont",
    senderEmail: "p.dumont@sfr.fr",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    daysAgo: 7,
  },
  {
    subject: "Educational discount not applied at checkout",
    body: "I verified my .edu email and received the educational discount approval email, but was charged full price at checkout ($99 instead of $49). Please apply the discount or refund the difference.",
    senderName: "Zara Ahmed",
    senderEmail: "z.ahmed@university.edu",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    daysAgo: 10,
  },
  {
    subject: "Account hacked — charges I didn't make",
    body: "My account was accessed without my permission and my payment method was used to upgrade to the Enterprise plan. I've reset my password and enabled 2FA. Please reverse the unauthorised charges.",
    senderName: "Marcus Webb",
    senderEmail: "marcus.webb@yahoo.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    daysAgo: 0,
  },
  {
    subject: "Refund — service not available in my country",
    body: "After purchasing, I discovered that the features I need are geo-restricted and not available in my country (Vietnam). This was not disclosed on the pricing page. Requesting a full refund.",
    senderName: "Nguyen Thi Lan",
    senderEmail: "lan.nguyen@vietmail.vn",
    status: "CLOSED",
    category: "REFUND_REQUEST",
    daysAgo: 29,
  },

  // More GENERAL_QUESTION
  {
    subject: "Can I white-label the product for my clients?",
    body: "I'm an agency and I'd like to offer your product under my own branding to clients. Do you have a white-label or reseller programme? If so, what are the terms?",
    senderName: "Agency Director, PixelWorks",
    senderEmail: "director@pixelworks.agency",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 2,
  },
  {
    subject: "Does your platform support multi-currency?",
    body: "We operate in 12 countries and need to display pricing in local currencies. Does your platform support multi-currency display and reporting natively?",
    senderName: "Global Ops, Tradex",
    senderEmail: "globalops@tradex.com",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 1,
  },
  {
    subject: "Pen test — permission to test our instance",
    body: "Our security policy requires us to perform an annual penetration test. We'd like written permission to conduct a pentest against our own organisation's instance. Who should we contact?",
    senderName: "CISO, Fortify Capital",
    senderEmail: "ciso@fortifycapital.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 14,
  },
  {
    subject: "How to set up custom roles and permissions",
    body: "We need granular role-based access control. For example, some users should be able to view reports but not export them. Can you walk me through the custom roles setup?",
    senderName: "IT Admin, Cascade Corp",
    senderEmail: "itadmin@cascadecorp.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 18,
  },
  {
    subject: "Minimum contract length for Enterprise?",
    body: "We're evaluating Enterprise plans. What is the minimum contract commitment — annual only, or are shorter terms (quarterly, monthly) available at a different rate?",
    senderName: "VP Procurement, Apex Global",
    senderEmail: "procurement@apexglobal.com",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 39,
  },
  {
    subject: "Is customer data used to train AI models?",
    body: "Our privacy policy team needs to know whether any data we process through your platform is used to train machine learning or AI models. If so, is there an opt-out?",
    senderName: "Privacy Officer, MedData GmbH",
    senderEmail: "privacy@meddata.de",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 0,
  },
  {
    subject: "Uptime SLA for the Business plan",
    body: "What is the guaranteed uptime SLA for the Business plan? We need at least 99.9% uptime for our use case and need this documented for internal approval.",
    senderName: "Procurement, BridgeOps",
    senderEmail: "procurement@bridgeops.co",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    daysAgo: 3,
  },
  {
    subject: "How to grant read-only access to an auditor",
    body: "We need to give an external auditor temporary read-only access to our workspace for a two-week period. They should see reports and logs but not be able to change anything.",
    senderName: "Finance Director, Aldgate Partners",
    senderEmail: "finance@aldgatepartners.co.uk",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    daysAgo: 20,
  },
  {
    subject: "Does the API support batch operations?",
    body: "We need to update 50,000 records in one go. Does your API support batch updates in a single request, or do we need to call the endpoint for each record individually?",
    senderName: "Data Engineer, Masscale",
    senderEmail: "data@masscale.io",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    daysAgo: 41,
  },

  // More null category
  {
    subject: "Compliment — exceptional support experience",
    body: "I just wanted to pass on my compliments. Your support agent Sarah went completely above and beyond yesterday to help us recover data we thought was lost. Give her a raise!",
    senderName: "Daniel Meyer",
    senderEmail: "d.meyer@kleinesfirma.at",
    status: "CLOSED",
    category: null,
    daysAgo: 27,
  },
  {
    subject: "Press inquiry — interview request",
    body: "I'm a journalist writing about SaaS helpdesk tools for TechCrunch. I'd love to arrange a brief interview with someone from your product or leadership team. Please connect me with your PR contact.",
    senderName: "Journalist, TechCrunch",
    senderEmail: "press@techcrunch.com",
    status: "RESOLVED",
    category: null,
    daysAgo: 16,
  },
  {
    subject: "Partnership proposal",
    body: "We're building a complementary tool and believe there's a strong integration opportunity. We'd love to explore a formal technology partnership. Who should we speak to?",
    senderName: "BD, Synergy Tools",
    senderEmail: "bd@synergytools.com",
    status: "OPEN",
    category: null,
    daysAgo: 5,
  },
  {
    subject: "Session timeout too short",
    body: "Our users are frequently logged out mid-work because the session timeout is set to 15 minutes. Is there a setting to extend this, or can it be configured per-workspace?",
    senderName: "Ops Lead, Workhive",
    senderEmail: "ops@workhive.app",
    status: "RESOLVED",
    category: null,
    daysAgo: 12,
  },
  {
    subject: "Keyboard shortcuts not working on Linux",
    body: "None of the documented keyboard shortcuts work on my Ubuntu 22.04 machine with Firefox. On my MacBook they work fine. Is this a known Linux/Firefox compatibility issue?",
    senderName: "Developer, OpenSource Labs",
    senderEmail: "dev@opensource-labs.org",
    status: "OPEN",
    category: null,
    daysAgo: 2,
  },
];

async function main() {
  console.log(`Seeding ${tickets.length} tickets...`);

  await prisma.ticket.createMany({
    data: tickets.map((t) => ({
      subject: t.subject,
      body: t.body,
      senderName: t.senderName,
      senderEmail: t.senderEmail,
      status: t.status,
      category: t.category ?? undefined,
      createdAt: new Date(Date.now() - t.daysAgo * 24 * 60 * 60 * 1000),
    })),
  });

  const total = await prisma.ticket.count();
  console.log(`Done. Total tickets in DB: ${total}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
